//public is a keyword to define access level
//known as access modifier, there are couple of them we will learn later
//private(meaning it's accessible in same class)
//If you not use public on variable(or method)
//It's automatically private
//class : indicate this is a class
//phone : identifier ,the name of the class
// { any code need to go in here ,can not go outsitde }
// The momenet a class exists, it can be a DataType
// meaning , you can create a variable of that type
// you can create a new instance (object) of that type and assign to the variable
// and much more
public class Phone{
    // a phone has below 
    // attributes or characteristics 
    // brand, price, memorySize
    // instance variable | field
    // 
    public String brand ;
    public Decimal price ;
    public Integer memorySize;
}