// Declare and initialize an Integer variable. 
// checks if a given integer is positive, negative, or zero. 
// If the number is positive, the program should print "Positive." 
// If the number is negative, the program should print “negative”
// Else print Zero


String score = 'Positive';

if(score == 'Negative') {
    System.debug('NEGATIVE'); 
}else if(score == 'Positive'){
    System.debug('POSITIVE'); 
}else{
    System.debug('ZERO'); 
}

